version: '3.8'

services:
  db:
    image: postgres:13
    container_name: hotel-guide-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: hotel_guide
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel-guide-network

  # Eğer uygulamanızı Docker içinde çalıştıracaksanız
  app:
    build: .
    container_name: hotel-guide-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - hotel-guide-network

volumes:
  postgres_data:
    driver: local

networks:
  hotel-guide-network:
    driver: bridge
