version: '3.8'

services:
  db:
    image: postgres:13
    container_name: hotel-guide-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel-guide-network

  rabbitmq:
    image: rabbitmq:management
    container_name: hotel-guide-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    ports:
      - "5672:5672"  # RabbitMQ default AMQP port
      - "15672:15672"  # RabbitMQ management plugin UI port
    networks:
      - hotel-guide-network

  app:
    build: .
    container_name: hotel-guide-app
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - hotel-guide-network
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  hotel-guide-network:
    driver: bridge
